name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.22' ]

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: CGO_ENABLED=1 go test -v -race ./...

    - name: GoLang CI Lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: latest
        only-new-issues: true
        args: --timeout=5m
